"""create alerts table

Revision ID: 9f5211c911eb
Revises: 
Create Date: 2026-07-25 23:36:34.012645
"""
from alembic import op
import sqlalchemy as sa


revision = '9f5211c911eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('txn_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('predicted_label', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_customer_id'), 'alerts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_alerts_txn_id'), 'alerts', ['txn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_txn_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_customer_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
